### PR TITLE
Story 001 tompaana 36

### PR DESCRIPTION
**Pull request by tompaana**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/43)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 159 of 269 files at r1.
Review status: 84 of 153 files reviewed at latest revision, 20 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/src/main/AndroidManifest.xml, line 16 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99OYy_0a7YaQdp01yx:-K99OYy_0a7YaQdp01yy:1146121709) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/AndroidManifest.xml#L16)):_
Since this defaults to true why did we need to explicitly include it?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java, line 39 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99dmYRONYZqYSoWciA:-K99dmYSylL2WrdY9j6a:692881268) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java#L39)):_
Since we have a work around do we need this method anymore?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java, line 80 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99xohLnl_BqV_QugjK:-K99xohM0cXoIWZBjMj_:2043345006) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java#L80)):_
/the not yet/not yet

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java, line 92 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99yKjR8obMmJ8gADEI:-K99yKjR8obMmJ8gADEJ:103491384) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java#L92)):_
So this is still the old design. In the new design we would only be advertising the bluetoothMacAddress, not a peer ID or a peer name, correct? So are we just checking in this code to put a close on the refactoring before starting to work on a design that complies with the new spec?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 24 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99Zlyfx94WcaUrFPH7:-K99ZlyguJ9BVU4f2oNo:-1762724423) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L24)):_
/ode/code/

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 29 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99ZsvA3nY64QAoTWZj:-K99ZsvBulvOWnJt7M4s:-826430641) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L29)):_
Wouldn't it be simpler to assign an enum to the modes? I realize at the native layer they are just ints but they aren't terribly meaningful to devs in int form.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 39 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99_5BQ25EMKxn96_jd:-K99_5BQ25EMKxn96_je:-141733754) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L39)):_
/BroadCast/Broadcast/

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 65 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99_aCbhbSSfDQl-TZB:-K99_aCbhbSSfDQl-TZC:-1562309480) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L65)):_
/excepts/except

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 66 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99_d0PDCz_9JDswBHR:-K99_d0PDCz_9JDswBHS:-638176922) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L66)):_
remove 'the'

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 103 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99aEWSXxQABjLTAtPJ:-K99aEWTNHWSRbbJEa82:1666543510) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L103)):_
Remove 'a'

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 109 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99aSJ_QjNKU3tBklYd:-K99aSJ_QjNKU3tBklYe:-752033393) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L109)):_
Are you somehow guaranteeing that BluetoothManager can only be run from a single thread or is this a race condition?

Time 0 - A call to isBluetoothSupported is made and this calls mListeners.size(), gets a 0 and then is swapped out for another thread.
Time 1 - Someone calls bind()
Time 2 - The thread from Time 0 is swapped back in, still thinks mListeners.size() is 0 and so calls deinitialize.

Is there another way to detect if Bluetooth is supported without having to initialize the adapter? I.e. along the lines of isBleSupported?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 137 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99bUsSEYw6W_uwk-iO:-K99bUsSEYw6W_uwk-iP:1075961573) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L137)):_
From a style perspective I would probably have written this as:

``` Java
if (!CommonUtils.isLollipopOrHigher()) {
  Log.d(...);
  return false;
}

return mBluetoothAdapter.isMultipleAdvertisementSupported();
```

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 176 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99cXrqV7DdtsA2F2qk:-K99cXrrflLWJ4lIMbnS:-1398747252) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L176)):_
I wonder what happens if getString is called on a Lollipop or higher device that doesn't have Bluetooth?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 37 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A2P1suztIRRVxcuKd:-K9A2P1suztIRRVxcuKe:-1245822159) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L37)):_
Since we aren't using this is the plan to keep it around for when Google inevitably breaks our work around? If so we should probably mark it as something we really aren't going to test or take responsibility for right now.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 92 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A3-SKOJZJ6rG0s3x9:-K9A3-SKOJZJ6rG0s3xA:-1458002566) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L92)):_
/AD/AID

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 95 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A3AEUHruQ9nXKINmn:-K9A3AEVVdlJCrau2SuQ:796541175) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L95)):_
I assume values like this go away when we switch to the new spec?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 195 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A44Kd60blh41c4T5p:-K9A44Kd60blh41c4T5q:1855568502) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L195)):_
There is no possibility that this method could be called twice on two different threads?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BleScanner.java, line 184 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A1fNBrUaqLmVArt-J:-K9A1fNCXLrPcpnCWb9U:1683700850) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BleScanner.java#L184)):_
I thought that batch results are sent if we go to low power? I also thought that we could preferentially set the settings to use batch results? My understanding is that batched results saves power. So if we aren't going to support this call back then doesn't this, at a minimum, mean we can never use low power mode?

---

_[BtConnectorLib/LICENSE, line 1 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99NYuhlz3-BBQcX5Ho:-K99NYuhlz3-BBQcX5Hp:-1552299909) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/LICENSE#L1)):_
We have a license at the root of the project. Why is there a second license file here?

---

_[BtConnectorLib/settings.gradle, line 2 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99O0ffxeKN_DTiCDd-:-K99O0fgTmOxBiuKCCRT:1594034194) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/settings.gradle#L2)):_
There are no breaking API changes? Or are we not using SEMVER?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43)_

**Comment by yaronyg** [comment]
@tompaana Please see my question in slack. That will tell me if I should continue with the code review or wait.

**Comment by tompaana** [comment]
Review status: 80 of 153 files reviewed at latest revision, 20 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/src/main/AndroidManifest.xml, line 16 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99OYy_0a7YaQdp01yx:-K9MW8G6QKNEme8v_Jbo:-1343805365) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/AndroidManifest.xml#L16)):_
Valid point. Must've ignored/missed that line. Might be generated by IDE.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java, line 39 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99dmYRONYZqYSoWciA:-K9MX5v9DyCSX-kP7ZKH:277982344) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java#L39)):_
No. (Although there is a native test that depends on it.) But I were to decide I'd keep it around.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java, line 80 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99xohLnl_BqV_QugjK:-K9MXZc__bgRk2um6O5U:1758359711) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java#L80)):_
Fixed.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java, line 92 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99yKjR8obMmJ8gADEI:-K9MXj9kSBk4rV3EkiI2:677251276) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/AbstractBluetoothConnectivityAgent.java#L92)):_
Yes.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 24 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99Zlyfx94WcaUrFPH7:-K9MXvHKLWZ1hfXl-TJ_:1505943545) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L24)):_
/ode/mode/ actually - fixed

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 29 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99ZsvA3nY64QAoTWZj:-K9MY9MyKBr3t_xinM7x:1100096970) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L29)):_
This callback just relays the native event (which uses int). The mode is only handled internally. I'd keep it as it is.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 39 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99_5BQ25EMKxn96_jd:-K9MYdBdiu4zDkBrT-yb:1758359711) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L39)):_
Fixed.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 65 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99_aCbhbSSfDQl-TZB:-K9MYqiXGQ4KTSZNiRkz:1758359711) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L65)):_
Fixed.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 66 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99_d0PDCz_9JDswBHR:-K9MYv9rUlC3F0BhAZNK:1758359711) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L66)):_
Fixed.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 103 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99aEWSXxQABjLTAtPJ:-K9MZ1gV9FuToKyZT_yS:1758359711) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L103)):_
Fixed.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 109 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99aSJ_QjNKU3tBklYd:-K9M_dZsIQjeStdNt9pO:1751789497) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L109)):_
Found a simpler way. Fixed.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 137 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99bUsSEYw6W_uwk-iO:-K9M_hhUrpMMgrW6dGNV:-1458314033) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L137)):_
Age old argument. I used to prefer that style, but then I hit my head or something and switched to preferring a single return point for some reason. If I changed that, I would have to do myriad of similar changes for the sake of consistency. Let's leave it as it is, ok?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java, line 176 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99cXrqV7DdtsA2F2qk:-K9MaNpl6SgrxY6ictdG:1436874348) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothManager.java#L176)):_
"The corresponding content URI, or null if not present" http://developer.android.com/intl/reference/android/provider/Settings.Secure.html#getString%28android.content.ContentResolver,%20java.lang.String%29

Null is handled gracefully.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 37 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A2P1suztIRRVxcuKd:-K9MaiV1UVrLnCIKZ9lW:-589676075) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L37)):_
Yes and note added.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 92 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A3-SKOJZJ6rG0s3x9:-K9MbyW1Ksvng2L5bGZC:-1344523659) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L92)):_
I actually meant "ad" as in advertisement. Not ok?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 95 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A3AEUHruQ9nXKINmn:-K9Mc88CAJk1lN5fBzFe:677251276) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L95)):_
Yes.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 195 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A44Kd60blh41c4T5p:-K9McHJjIJ7kgi-y84Ci:-1439402365) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L195)):_
"There can be only one." BlePeerDiscoverer instance that is.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BleScanner.java, line 184 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A1fNBrUaqLmVArt-J:-K9McWD-1wsDZNMBpjE3:-554281388) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BleScanner.java#L184)):_
I think I simply forgot to implement that, because onScanResult works on all power settings. Implemented now.

---

_[BtConnectorLib/LICENSE, line 1 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99NYuhlz3-BBQcX5Ho:-K9MeKOFN80ShKGqHCjw:1740281843) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/LICENSE#L1)):_
Removed.

---

_[BtConnectorLib/settings.gradle, line 2 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99O0ffxeKN_DTiCDd-:-K9MeQFtClzdRbS5WMdy:-148132104) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/settings.gradle#L2)):_
There are. What is SEMVER?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43)_

**Comment by tompaana** [comment]
Meant to have /Fixed/Fixes/

---

Review status: 80 of 153 files reviewed at latest revision, 20 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-:-K9MeholX-F6vT4xPy2i:1299238573)_

**Comment by yaronyg** [comment]
Review status: 80 of 153 files reviewed at latest revision, 3 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/src/main/AndroidManifest.xml, line 16 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99OYy_0a7YaQdp01yx:-K9Sn5PqpGBCOkgyLG6a:-1436217416) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/AndroidManifest.xml#L16)):_
If the IDE put it in then don't worry about it.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 195 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K9A44Kd60blh41c4T5p:-K9Snhy5Y6D-eH1qOiye:-1610689334) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L195)):_
The object may be static but what happens if there is a call on it from two different threads? Static objects, I believe, can be invoked across arbitrary numbers of threads?

---

_[BtConnectorLib/settings.gradle, line 2 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43#-K99O0ffxeKN_DTiCDd-:-K9SnxuIVNJzT3rW7gQM:135908693) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/b73821382f5146c6e760a65e27ff8ae5d4f71133/BtConnectorLib/settings.gradle#L2)):_
http://semver.org/ is SEMVER. It's how versioning works in systems like Node. Adoption in Java has been mixed but I would tend to think we should use it here.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/43)_

**Pull request merged**
