### PR TITLE
Refactor BluetoothClientThread

### PR DESCRIPTION
**Pull request by evabishchevich**
Issue #105

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/106)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fa010d0)

**Comment by ThaliTester** [comment]
Test 100332223 (fa010d0) build started.

**Comment by ThaliTester** [comment]
Test (Success) 100332223 build is completed (fa010d0)

See https://github.com/ThaliTester/TestResults/tree/100332223fa010d0_Refactor_BluetoothClientThread_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 100332223fa010d0(fa010d0) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/100332223fa010d0_Refactor_BluetoothClientThread_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
Already included in #107

**Pull request closed without merging**
