### PR TITLE
Changed handshake process

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/104)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6c7459f)

**Comment by ThaliTester** [comment]
Test 99247454 (6c7459f) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99247454 build is completed (6c7459f)

See https://github.com/ThaliTester/TestResults/tree/992474546c7459f_Changed_handshake_process_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 992474546c7459f(6c7459f) has failed

See https://github.com/ThaliTester/TestResults/tree/992474546c7459f_Changed_handshake_process_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (49148c1)

**Comment by ThaliTester** [comment]
Test 99247454 (49148c1) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99247454 build is completed (49148c1)

See https://github.com/ThaliTester/TestResults/tree/9924745449148c1_Changed_handshake_process_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 9924745449148c1(49148c1) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/9924745449148c1_Changed_handshake_process_evabishchevich/ for the logs

**Comment by yaronyg** [comment]
Only one issue jumped out at me and I assume you'll do the right thing with it so once it's resolved then :lgtm: 

---

Reviewed 15 of 18 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/PeerProperties.java, line 56 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/104#-KZvyy8H2V_U6Yjaf20k:-KZvyy8H2V_U6Yjaf20l:b-kdjrhd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/49148c168bd56185c20c8d7d73ca1e215a115326/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/PeerProperties.java#L56)):*
> ```Java
>     }
> 
>     private void tryToSetExtraInfo(int extraInformation) {
> ```

If someone tries to set extra info (e.g. generation) to a value that will do nothing then shouldn't an error be returned? E.g. fi extraInformation >= PeerProperties.NO_EXTRA_INFORMATION should that be an error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/104#-:-KZvzcHYIL_6fTIxgziM:b-kfty38)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2335eeb)

**Comment by ThaliTester** [comment]
Test 99247454 (2335eeb) build started.

**Comment by evabishchevich** [comment]
Review status: 19 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/PeerProperties.java, line 56 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/104#-KZvyy8H2V_U6Yjaf20k:-K_-TmRXjwin16HlbKDH:b-ssorgg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/49148c168bd56185c20c8d7d73ca1e215a115326/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/PeerProperties.java#L56)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

If someone tries to set extra info (e.g. generation) to a value that will do nothing then shouldn't an error be returned? E.g. fi extraInformation >= PeerProperties.NO_EXTRA_INFORMATION should that be an error?
</blockquote></details>

Added an exception. Written test for that case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/104)*

**Comment by ThaliTester** [comment]
Test (Success) 99247454 build is completed (2335eeb)

See https://github.com/ThaliTester/TestResults/tree/992474542335eeb_Changed_handshake_process_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 992474542335eeb(2335eeb) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/992474542335eeb_Changed_handshake_process_evabishchevich/ for the logs

**Pull request merged**
