### PR TITLE
Vasilevskayaem 1418

### PR DESCRIPTION
**Pull request by vasilevskayaem**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/95)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (433f0e1)

**Comment by ThaliTester** [comment]
Test (Fail) 91925006 build is completed (433f0e1)

See https://github.com/ThaliTester/TestResults/tree/91925006433f0e1_Vasilevskayaem_1418_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f8b3911)

**Comment by ThaliTester** [comment]
Test (Fail) 91925006 build is completed (f8b3911)

See https://github.com/ThaliTester/TestResults/tree/91925006f8b3911_Vasilevskayaem_1418_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c306e39)

**Comment by ThaliTester** [comment]
Test 91925006 (c306e39) build started.

**Comment by ThaliTester** [comment]
Test (Success) 91925006 build is completed (c306e39)

See https://github.com/ThaliTester/TestResults/tree/91925006c306e39_Vasilevskayaem_1418_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (54ad4d8)

**Comment by ThaliTester** [comment]
Test 91925006 (54ad4d8) build started.

**Comment by ThaliTester** [comment]
Test (Success) 91925006 build is completed (54ad4d8)

See https://github.com/ThaliTester/TestResults/tree/9192500654ad4d8_Vasilevskayaem_1418_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 91925006c306e39(c306e39) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/91925006c306e39_Vasilevskayaem_1418_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 9192500654ad4d8(54ad4d8) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/9192500654ad4d8_Vasilevskayaem_1418_vasilevskayaem/ for the logs

**Comment by evabishchevich** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/95#-:-KYrf_4xLt3GgnDte866:bg7igk9)*

**Review by larryonoff — APPROVED** [review]
there're some syntax issues, that linter fix if it is. But we don't have linter.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aaac2e8)

**Comment by ThaliTester** [comment]
Test 91925006 (aaac2e8) build started.

**Comment by ThaliTester** [comment]
Test (Success) 91925006 build is completed (aaac2e8)

See https://github.com/ThaliTester/TestResults/tree/91925006aaac2e8_Vasilevskayaem_1418_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 91925006aaac2e8(aaac2e8) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/91925006aaac2e8_Vasilevskayaem_1418_vasilevskayaem/ for the logs

**Pull request merged**
