### PR TITLE
Nullify bluetooth socket during closing process

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/109)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (21cb5f7)

**Comment by ThaliTester** [comment]
Test 102928222 (21cb5f7) build started.

**Comment by ThaliTester** [comment]
Test (Success) 102928222 build is completed (21cb5f7)

See https://github.com/ThaliTester/TestResults/tree/10292822221cb5f7_Nullify_bluetooth_socket_during_closing_process_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
One more time about versions. I will remove "alpha" postfix when this code is in master branch

**Comment by ThaliTester** [comment]
Test 10292822221cb5f7(21cb5f7) has failed

See https://github.com/ThaliTester/TestResults/tree/10292822221cb5f7_Nullify_bluetooth_socket_during_closing_process_evabishchevich/ for the fail logs

**Comment by evabishchevich** [comment]
Test failed because of disabled Bluetooth

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (39dba27)

**Comment by ThaliTester** [comment]
Test 102928222 (39dba27) build started.

**Comment by ThaliTester** [comment]
Test (Success) 102928222 build is completed (39dba27)

See https://github.com/ThaliTester/TestResults/tree/10292822239dba27_Nullify_bluetooth_socket_during_closing_process_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 10292822239dba27(39dba27) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/10292822239dba27_Nullify_bluetooth_socket_during_closing_process_evabishchevich/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/109#-:-KbH2DjMDGY2xDEG8b7v:bnfp4nl)*

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/109#-:-KbJPaB58c31N9xxjnxE:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (bc5a03c)

**Comment by ThaliTester** [comment]
Test 102928222 (bc5a03c) build started.

**Comment by ThaliTester** [comment]
Test (Success) 102928222 build is completed (bc5a03c)

See https://github.com/ThaliTester/TestResults/tree/102928222bc5a03c_Nullify_bluetooth_socket_during_closing_process_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 102928222bc5a03c(bc5a03c) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/102928222bc5a03c_Nullify_bluetooth_socket_during_closing_process_evabishchevich/ for the logs

**Pull request merged**
