### PR TITLE
Initial commit with UT for DiscoveryManager and ConnectionManager

### PR DESCRIPTION
**Pull request by jareksl**
All changes done to the constructors should allow to inject mocked Context, BluetoothAdapter and SharedPreferences. All tests are the white box UT. There are also some changes done to the build.gradle and build.sh which are needed to allow to run tests on the CI

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/57)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 10 of 15 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/build.gradle, line 34 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFpwi-WDlbXuQGSY9CF:-KFpwi-XStpHhA8Y8U3M:-1001745254) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/build.gradle#L34)):_
Why are we including robolectric? I don't see us using any of its annotations anywhere. What is it being used for? I'm pretty ignorant about robolectric. Is it powerful enough to let your tests run on the desktop just by including it without any other references to it?

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 1 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFtadnvwnyDEgOIC636:-KFtadnwPpYlkeyFb8bY:-427555801) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L1)):_
It would be good to test that the constructor actually fails properly when it gets bogus arguments. I expect these tests to fail since we aren't really checking our arguments properly but that is why we have tests. :)

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 3 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFuCQKMbYSv5ijhS5_t:-KFuCQKNn6VyFnytfFvX:-1088047844) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L3)):_
I would have expected testing of getBluetoothMacAddress and verifyIdentityString. I was never clear if anyone still uses createIdentityString but if so then we need to test that as well.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 93 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFtQ9VDhxebzANPItvR:-KFtQ9VEkXD65TowDJBI:2130953557) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L93)):_
Wouldn't it be more robust, if other tests depend on Bluetooth being enabled to just put toggleBluetooth(true) into @before? I see it in @beforeclass but that brings up the problem you have here that if one tests messes with the state it breaks things for everyone else. Isn't that exactly the sort of thing that should be in @before?

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 335 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFuHZfTkiT3kbA6R4QW:-KFuHZfTkiT3kbA6R4QX:-563169588) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L335)):_
Don't we need to test that we actually can form a connection?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/ConnectionManager.java, line 120 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFuErbbq6S4D-rvRi_m:-KFuErbbq6S4D-rvRi_n:1688489156) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/ConnectionManager.java#L120)):_
I assume this constructor is just here for testing purposes? If so then it should be clearly marked as such. It's also not a great idea to replicate code the way we do here. Instead use something like http://stackoverflow.com/questions/285177/how-do-i-call-one-constructor-from-another-in-java to call the constructor above and then do the clean up for the two new arguments in this constructor. Alternatively you can get rid of this constructor and create two utility methods to set the Bluetooth connector and the preferences.

---

_[BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManagerSettingsTest.java, line 327 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFuaeqF-wElEuNI3unE:-KFuaeqGWpYsfN8NjVPk:-921999958) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManagerSettingsTest.java#L327)):_
We aren't going to support the WiFi direct code so strictly speaking we don't need this test. More to the point, if this test fails, we wouldn't do anything about it. I hate to get rid of code but I wonder if that wouldn't make sense as any issues with this test or the code would be ignored?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57)_

**Comment by jareksl** [comment]
Review status: 5 of 37 files reviewed at latest revision, 7 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/build.gradle, line 34 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFpwi-WDlbXuQGSY9CF:-KGB6m47SrU74k9kM0gS:1279014825) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/build.gradle#L34)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> Why are we including robolectric? I don't see us using any of its annotations anywhere. What is it being used for? I'm pretty ignorant about robolectric. Is it powerful enough to let your tests run on the desktop just by including it without any other references to it?</details>
> The robolectric was added at very beginning, when it hadn't been decided yet which testing framework to use. It is not needed anymore and will be removed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57)_

**Comment by yaronyg** [comment]
Reviewed 32 of 32 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 405 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KI0EEFrR3XMkZElMrlM:-KI0EEFrR3XMkZElMrlN:1622411300) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c350a19309b971aa0151de0b2ddca10692fc29ba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L405)):_

> ``` Java
> 
>             public void run() {
>                 Looper.prepare();
> ```

Why are we using a looper? Where is the message handler?

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 432 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KI0FAa6Et8vFjElxPec:-KI0FAa7Ll9ftqBuMYjx:1846697315) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c350a19309b971aa0151de0b2ddca10692fc29ba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L432)):_

> ``` Java
> 
>         // let's wait for connection timeout (additional time to ensure no other handler is called)
>         Thread.sleep(timeout + 20000);
> ```

Dude, our tests are going to take years if we have to keep shoving in 20 second time outs!

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 447 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KI0FIuvtLzkL6Nb0A_L:-KI0FIuvtLzkL6Nb0A_M:1577356333) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c350a19309b971aa0151de0b2ddca10692fc29ba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L447)):_

> ``` Java
> 
>         // let's wait for connection failure (additional time to ensure no other handler is called)
>         Thread.sleep(timeout + 10000);
> ```

You're killed me here! 70 seconds?!?!?!?

---

_[BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtilsTest.java, line 187 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KI0T3NykWd8D4iRg6tz:-KI0T3NykWd8D4iRg6u-:1046008814) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c350a19309b971aa0151de0b2ddca10692fc29ba/BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtilsTest.java#L187)):_

> ``` Java
>     // The tests below does not work due to the fact that the class BluetoothSocket
>     // is part of the android SDK. That means that is not available for unit testing by default.
>     // It has to be tested by instrumented tests
> ```

So then what's the plan for these tests?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57)_

**Comment by czyzm** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 1 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFtadnvwnyDEgOIC636:-KI1ZxLBgaRqTMpSLSTF:-723742319) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L1)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> It would be good to test that the constructor actually fails properly when it gets bogus arguments. I expect these tests to fail since we aren't really checking our arguments properly but that is why we have tests. :)
> </details>
> I've added such test.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 3 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFuCQKMbYSv5ijhS5_t:-KI1_4gL19jt1Pf3gfTs:1530814705) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L3)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> I would have expected testing of getBluetoothMacAddress and verifyIdentityString. I was never clear if anyone still uses createIdentityString but if so then we need to test that as well.
> </details>
> Those tests are added.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 335 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KFuHZfTkiT3kbA6R4QW:-KI1bGEHGhHyFYQ9A-xi:-1732794026) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/0dd4c16f0382b6eed65c21c0030b9c8aff7b0dba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L335)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> Don't we need to test that we actually can form a connection?
> </details>
> This needs to be done in coordinated tests.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 405 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KI0EEFrR3XMkZElMrlM:-KI1_CXzlrPlVlvwmRcS:741355374) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c350a19309b971aa0151de0b2ddca10692fc29ba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L405)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> Why are we using a looper? Where is the message handler?
> </details>
> We need to use it inside new thread in order to make the timeout count down timer working (BluetoothConnector.mConnectionTimeoutTimer). It is having its handler.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 432 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KI0FAa6Et8vFjElxPec:-KI1afw8Y-GqLbs2k1qT:105836096) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c350a19309b971aa0151de0b2ddca10692fc29ba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L432)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> Dude, our tests are going to take years if we have to keep shoving in 20 second time outs!
> </details>
> The instrumentation tests are quite heavy anyway (e.g. waiting for bluetooth to turn on etc.). Where possible I am checking state in short intervals until maximum timeout but here I just need to ensure that something is not done and this is why this timeout here.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 447 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KI0FIuvtLzkL6Nb0A_L:-KI1b6YLfnaldfEh1hOm:-1564117789) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c350a19309b971aa0151de0b2ddca10692fc29ba/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L447)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> You're killed me here! 70 seconds?!?!?!?
> </details>
> This part will be removed as it is not reliable (depending on device).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57)_

**Comment by jareksl** [comment]
_[BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtilsTest.java, line 187 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-KI0T3NykWd8D4iRg6tz:-KI2tBN3Dr4L9SeRASVf:-1380640767) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c350a19309b971aa0151de0b2ddca10692fc29ba/BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtilsTest.java#L187)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> So then what's the plan for these tests?</details>
> I will update the comment and remove not needed tests

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57)_

**Comment by yaronyg** [comment]
:lgtm:

<details><summary>

<i>Previously, jareksl (Jarek Słota) wrote…</i></summary>



> New commits in r2
> </details>

---

Reviewed 1 of 1 files at r4, 3 of 3 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/57#-:-KIVF24uc_S0C3UdfHTE:1417088721)_

**Pull request merged**
