### PR TITLE
Add connect time measurement test

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/107)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ddbfdb4)

**Comment by ThaliTester** [comment]
Test 100443495 (ddbfdb4) build started.

**Comment by ThaliTester** [comment]
Test (Success) 100443495 build is completed (ddbfdb4)

See https://github.com/ThaliTester/TestResults/tree/100443495ddbfdb4_Add_connect_time_measurement_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 100443495ddbfdb4(ddbfdb4) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/100443495ddbfdb4_Add_connect_time_measurement_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6aac6d1)

**Comment by ThaliTester** [comment]
Test 100443495 (6aac6d1) build started.

**Comment by ThaliTester** [comment]
Test (Success) 100443495 build is completed (6aac6d1)

See https://github.com/ThaliTester/TestResults/tree/1004434956aac6d1_Add_connect_time_measurement_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 1004434956aac6d1(6aac6d1) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/1004434956aac6d1_Add_connect_time_measurement_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9b0b18a)

**Comment by ThaliTester** [comment]
Test 100443495 (9b0b18a) build started.

**Comment by ThaliTester** [comment]
Test (Success) 100443495 build is completed (9b0b18a)

See https://github.com/ThaliTester/TestResults/tree/1004434959b0b18a_Add_connect_time_measurement_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 1004434959b0b18a(9b0b18a) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/1004434959b0b18a_Add_connect_time_measurement_test_evabishchevich/ for the logs

**Comment by yaronyg** [comment]
Please see my comments. I'm a bit confused, did this actually fix the port conflict problem? Did it at least prove that the port conflict problem exists?

---

Reviewed 13 of 20 files at r1, 8 of 9 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothClientThread.java, line 319 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-KahUcWdFgNnhxveBaiK:-KahUcWeIJ84uzi6Ivt2:bh2f4yp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/9b0b18ac923bab0a3633b7fa85c2cc54c55b8948/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothClientThread.java#L319)):*
> ```Java
>             socketConnectSucceeded = connect(mInsecureRfcommSocketPort, socketConnectAttemptNo);
>             if (!socketConnectSucceeded) {
>                 if (mInsecureRfcommSocketPort >= 0 && !mIsShuttingDown) {
> ```

I'm confused. What is the point of allowing us to set the RFComm Socket Port when there doesn't seem to be any code in BluetoothServerThread to set the port in createServerSocket? Do we somehow know what port the server will always use and thus can avoid that port on the client? I'm a bit confused.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtils.java, line 355 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-KahRei5gUCJnjG8SmUv:-KahRei5gUCJnjG8SmUw:bf3sz9s) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/9b0b18ac923bab0a3633b7fa85c2cc54c55b8948/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtils.java#L355)):*
> ```Java
>     }
> 
>     private static BluetoothSocket ejectBluetoothSocket(BluetoothServerSocket socket) throws NoSuchFieldException, IllegalAccessException {
> ```

NB: The name seems a bit misleading. This looks like it just returns the socket while the name implies that it will actually cause the socket to be ejected.

---

*[NativeTestApp/app/build.gradle, line 42 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-KahQGgHEJMdRWBZpDc2:-KahQGgHEJMdRWBZpDc3:bh3ox08) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/9b0b18ac923bab0a3633b7fa85c2cc54c55b8948/NativeTestApp/app/build.gradle#L42)):*
> ```Gradle
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     compile 'com.android.support:appcompat-v7:23.1.1'
>     compile(group: 'org.thaliproject.p2p.btconnectorlib', name: 'btconnectorlib2', version: '0.3.8-alpha2', ext: 'aar')
> ```

What is the logic we are using for deciding when a release gets a number (e.g. 0.3.8) versus some kind of label (e.g. 0.3.8-alpha2)?

---

*[NativeTestApp/app/src/main/java/org/thaliproject/nativetest/app/model/PeerAndConnectionModel.java, line 129 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-KahQkilHG-Wg2Birw50:-KahQkilHG-Wg2Birw51:bbsoah0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/9b0b18ac923bab0a3633b7fa85c2cc54c55b8948/NativeTestApp/app/src/main/java/org/thaliproject/nativetest/app/model/PeerAndConnectionModel.java#L129)):*
> ```Java
>             try {
>                 if (mPeers.get(i).equals(peerProperties)) {
> //                    mPeers.get(i).setName(peerProperties.getName());
> ```

NB: Why leave it even commented out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-:-KahV5SeVfPpH6adwmxN:be29dq)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (00862be)

**Comment by ThaliTester** [comment]
Test 100443495 (00862be) build started.

**Comment by evabishchevich** [comment]
@yaronyg I understand your confusion. This PR didn't fix and didn't prove port conflict problem. The main goal of this PR is adding the connection measurement test to NativeTestApp. There is also some refactorings that I did during my RFCOMM sockets investigation. Right now it is not the most prioritized task so the work was stopped for a while. I didn't want to lose this work so created this PR

---

Review status: 20 of 25 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothClientThread.java, line 319 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-KahUcWdFgNnhxveBaiK:-Kaln3vUvcIiSrV8g2TW:b-eao7wi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/9b0b18ac923bab0a3633b7fa85c2cc54c55b8948/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothClientThread.java#L319)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

I'm confused. What is the point of allowing us to set the RFComm Socket Port when there doesn't seem to be any code in BluetoothServerThread to set the port in createServerSocket? Do we somehow know what port the server will always use and thus can avoid that port on the client? I'm a bit confused.
</blockquote></details>

It's just refactoring of the previous code. Looks like changing of the port doesn't help. Based on my investigations I even can say that there is no sense to change the port, because we will communicate via port that the server listens on the other side.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtils.java, line 355 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-KahRei5gUCJnjG8SmUv:-KalqDFLuycvr6KO1wQX:bzeja2i) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/9b0b18ac923bab0a3633b7fa85c2cc54c55b8948/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtils.java#L355)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

NB: The name seems a bit misleading. This looks like it just returns the socket while the name implies that it will actually cause the socket to be ejected.
</blockquote></details>

Good catch. Thank you

---

*[NativeTestApp/app/build.gradle, line 42 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-KahQGgHEJMdRWBZpDc2:-Kalnp8UOTE2OUF2byqe:b-h3nn50) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/9b0b18ac923bab0a3633b7fa85c2cc54c55b8948/NativeTestApp/app/build.gradle#L42)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

What is the logic we are using for deciding when a release gets a number (e.g. 0.3.8) versus some kind of label (e.g. 0.3.8-alpha2)?
</blockquote></details>

We mark library without alpha or beta only when the code is in master branch. There is no procedure to decide when we increase the first, the second or the third digit. Previously I used alpha or beta to provide a raw version to the bintray while my code was on review to give others opportunity to have needed fixes. We should describe the rules when and how to increase build number to have standardized process.

---

*[NativeTestApp/app/src/main/java/org/thaliproject/nativetest/app/model/PeerAndConnectionModel.java, line 129 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-KahQkilHG-Wg2Birw50:-Kalql9yQ-jGQpoV6YPY:b-pixxt5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/9b0b18ac923bab0a3633b7fa85c2cc54c55b8948/NativeTestApp/app/src/main/java/org/thaliproject/nativetest/app/model/PeerAndConnectionModel.java#L129)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

NB: Why leave it even commented out?
</blockquote></details>

We don't need it since we don't have a name field in the peer properties class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-:-KalleAXvpvU9qsaFl58:blwncvi)*

**Comment by ThaliTester** [comment]
Test (Success) 100443495 build is completed (00862be)

See https://github.com/ThaliTester/TestResults/tree/10044349500862be_Add_connect_time_measurement_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 10044349500862be(00862be) has failed

See https://github.com/ThaliTester/TestResults/tree/10044349500862be_Add_connect_time_measurement_test_evabishchevich/ for the fail logs

**Comment by evabishchevich** [comment]
Test failed because of disabled bluetooth

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (301874c)

**Comment by ThaliTester** [comment]
Test 100443495 (301874c) build started.

**Comment by ThaliTester** [comment]
Test (Success) 100443495 build is completed (301874c)

See https://github.com/ThaliTester/TestResults/tree/100443495301874c_Add_connect_time_measurement_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 100443495301874c(301874c) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/100443495301874c_Add_connect_time_measurement_test_evabishchevich/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[NativeTestApp/app/build.gradle, line 42 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-KahQGgHEJMdRWBZpDc2:-KamdrArGfwVqh3TfSOV:bbvj46q) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/9b0b18ac923bab0a3633b7fa85c2cc54c55b8948/NativeTestApp/app/build.gradle#L42)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

We mark library without alpha or beta only when the code is in master branch. There is no procedure to decide when we increase the first, the second or the third digit. Previously I used alpha or beta to provide a raw version to the bintray while my code was on review to give others opportunity to have needed fixes. We should describe the rules when and how to increase build number to have standardized process.
</blockquote></details>

Let's not over think it though. :) I was just curious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/107#-:-Kame0PpYwdNP99yrhxb:bnfp4nl)*

**Pull request merged**
