### PR TITLE
CI test

### PR DESCRIPTION
**Pull request by czyzm**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/67)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b919129)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (b919129)

See https://github.com/ThaliTester/TestResults/tree/72314330b919129_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330b919129(b919129) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330b919129_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f5994ee)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (f5994ee)

See https://github.com/ThaliTester/TestResults/tree/72314330f5994ee_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330f5994ee(f5994ee) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/72314330f5994ee_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bed5cba)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (bed5cba)

See https://github.com/ThaliTester/TestResults/tree/72314330bed5cba_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330bed5cba(bed5cba) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330bed5cba_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a4348a2)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (a4348a2)

See https://github.com/ThaliTester/TestResults/tree/72314330a4348a2_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330a4348a2(a4348a2) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/72314330a4348a2_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (baefe72)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (baefe72)

See https://github.com/ThaliTester/TestResults/tree/72314330baefe72_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330baefe72(baefe72) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330baefe72_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c322265)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (c322265)

See https://github.com/ThaliTester/TestResults/tree/72314330c322265_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330c322265(c322265) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330c322265_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fc76197)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (fc76197)

See https://github.com/ThaliTester/TestResults/tree/72314330fc76197_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330fc76197(fc76197) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330fc76197_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (33ec147)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (33ec147)

See https://github.com/ThaliTester/TestResults/tree/7231433033ec147_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433033ec147(33ec147) has failed

See https://github.com/ThaliTester/TestResults/tree/7231433033ec147_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (99080a4)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (99080a4)

See https://github.com/ThaliTester/TestResults/tree/7231433099080a4_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433099080a4(99080a4) has failed

See https://github.com/ThaliTester/TestResults/tree/7231433099080a4_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8ce34d3)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (8ce34d3)

See https://github.com/ThaliTester/TestResults/tree/723143308ce34d3_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 723143308ce34d3(8ce34d3) has failed

See https://github.com/ThaliTester/TestResults/tree/723143308ce34d3_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (48d1706)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (48d1706)

See https://github.com/ThaliTester/TestResults/tree/7231433048d1706_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433048d1706(48d1706) has failed

See https://github.com/ThaliTester/TestResults/tree/7231433048d1706_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (08444f5)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (08444f5)

See https://github.com/ThaliTester/TestResults/tree/7231433008444f5_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433008444f5(08444f5) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/7231433008444f5_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c6e12e6)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (c6e12e6)

See https://github.com/ThaliTester/TestResults/tree/72314330c6e12e6_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330c6e12e6(c6e12e6) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330c6e12e6_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5d716bc)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (5d716bc)

See https://github.com/ThaliTester/TestResults/tree/723143305d716bc_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 723143305d716bc(5d716bc) has failed

See https://github.com/ThaliTester/TestResults/tree/723143305d716bc_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (27d2cb4)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (27d2cb4)

See https://github.com/ThaliTester/TestResults/tree/7231433027d2cb4_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433027d2cb4(27d2cb4) has failed

See https://github.com/ThaliTester/TestResults/tree/7231433027d2cb4_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (57166e1)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (57166e1)

See https://github.com/ThaliTester/TestResults/tree/7231433057166e1_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433057166e1(57166e1) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/7231433057166e1_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (31aea01)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (31aea01)

See https://github.com/ThaliTester/TestResults/tree/7231433031aea01_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433031aea01(31aea01) has failed

See https://github.com/ThaliTester/TestResults/tree/7231433031aea01_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (49e1ea4)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (49e1ea4)

See https://github.com/ThaliTester/TestResults/tree/7231433049e1ea4_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0dc1997)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (0dc1997)

See https://github.com/ThaliTester/TestResults/tree/723143300dc1997_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433049e1ea4(49e1ea4) has failed

See https://github.com/ThaliTester/TestResults/tree/7231433049e1ea4_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
Test 723143300dc1997(0dc1997) has failed

See https://github.com/ThaliTester/TestResults/tree/723143300dc1997_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d9c2d09)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (d9c2d09)

See https://github.com/ThaliTester/TestResults/tree/72314330d9c2d09_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330d9c2d09(d9c2d09) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330d9c2d09_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (12bed78)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (12bed78)

See https://github.com/ThaliTester/TestResults/tree/7231433012bed78_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433012bed78(12bed78) has failed

See https://github.com/ThaliTester/TestResults/tree/7231433012bed78_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (42bf7a9)

**Comment by ThaliTester** [comment]
Test 7231433042bf7a9(42bf7a9) has failed

See https://github.com/ThaliTester/TestResults/tree/7231433042bf7a9_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (171bc24)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (171bc24)

See https://github.com/ThaliTester/TestResults/tree/72314330171bc24_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330171bc24(171bc24) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330171bc24_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f09ac10)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (f09ac10)

See https://github.com/ThaliTester/TestResults/tree/72314330f09ac10_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330f09ac10(f09ac10) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330f09ac10_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dc35b0f)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (dc35b0f)

See https://github.com/ThaliTester/TestResults/tree/72314330dc35b0f_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ebceebb)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (ebceebb)

See https://github.com/ThaliTester/TestResults/tree/72314330ebceebb_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330dc35b0f(dc35b0f) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330dc35b0f_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5350dbb)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (5350dbb)

See https://github.com/ThaliTester/TestResults/tree/723143305350dbb_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330ebceebb(ebceebb) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330ebceebb_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
Test 723143305350dbb(5350dbb) has failed

See https://github.com/ThaliTester/TestResults/tree/723143305350dbb_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (434ea2f)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (434ea2f)

See https://github.com/ThaliTester/TestResults/tree/72314330434ea2f_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330434ea2f(434ea2f) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330434ea2f_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3026ff3)

**Comment by ThaliTester** [comment]
Test 723143303026ff3(3026ff3) has failed

See https://github.com/ThaliTester/TestResults/tree/723143303026ff3_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9ec4627)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (9ec4627)

See https://github.com/ThaliTester/TestResults/tree/723143309ec4627_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 723143309ec4627(9ec4627) has failed

See https://github.com/ThaliTester/TestResults/tree/723143309ec4627_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (104b961)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (104b961)

See https://github.com/ThaliTester/TestResults/tree/72314330104b961_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330104b961(104b961) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330104b961_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c483f51)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (c483f51)

See https://github.com/ThaliTester/TestResults/tree/72314330c483f51_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330c483f51(c483f51) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330c483f51_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (201b184)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (201b184)

See https://github.com/ThaliTester/TestResults/tree/72314330201b184_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330201b184(201b184) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330201b184_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ac53991)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (ac53991)

See https://github.com/ThaliTester/TestResults/tree/72314330ac53991_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330ac53991(ac53991) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330ac53991_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7dd2999)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (7dd2999)

See https://github.com/ThaliTester/TestResults/tree/723143307dd2999_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 723143307dd2999(7dd2999) has failed

See https://github.com/ThaliTester/TestResults/tree/723143307dd2999_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c09f016)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (c09f016)

See https://github.com/ThaliTester/TestResults/tree/72314330c09f016_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330c09f016(c09f016) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330c09f016_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1de0613)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (1de0613)

See https://github.com/ThaliTester/TestResults/tree/723143301de0613_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8b78ad6)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (8b78ad6)

See https://github.com/ThaliTester/TestResults/tree/723143308b78ad6_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 723143301de0613(1de0613) has failed

See https://github.com/ThaliTester/TestResults/tree/723143301de0613_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
Test 723143308b78ad6(8b78ad6) has failed

See https://github.com/ThaliTester/TestResults/tree/723143308b78ad6_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a03b73e)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (a03b73e)

See https://github.com/ThaliTester/TestResults/tree/72314330a03b73e_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330a03b73e(a03b73e) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330a03b73e_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6d454a2)

**Comment by lesn1kk** [comment]
We get following error in CI:
Error: PR commit failed { [Error: socket hang up]
  defaultMessage: 'Internal Server Error',
  message: 'socket hang up',
  code: '500' } { user: 'thaliproject',
  repo: 'Thali_CordovaPlugin_BtLibrary',
  number: 67,
  body: 'Test (Success) 72314330 build is completed (6d454a2)\n\nSee https://github.com/ThaliTester/TestResults/tree/723143306d454a2_CI_test_czyzm/ for the logs' }

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aab8b1d)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (aab8b1d)

See https://github.com/ThaliTester/TestResults/tree/72314330aab8b1d_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330aab8b1d(aab8b1d) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/72314330aab8b1d_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8a74398)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4b8d2a7)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (8a74398)

See https://github.com/ThaliTester/TestResults/tree/723143308a74398_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (4b8d2a7)

See https://github.com/ThaliTester/TestResults/tree/723143304b8d2a7_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 723143308a74398(8a74398) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/723143308a74398_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 723143304b8d2a7(4b8d2a7) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/723143304b8d2a7_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (976de70)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (976de70)

See https://github.com/ThaliTester/TestResults/tree/72314330976de70_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330976de70(976de70) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330976de70_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f951e7a)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (f951e7a)

See https://github.com/ThaliTester/TestResults/tree/72314330f951e7a_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330f951e7a(f951e7a) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330f951e7a_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d0384b2)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (d0384b2)

See https://github.com/ThaliTester/TestResults/tree/72314330d0384b2_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330d0384b2(d0384b2) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330d0384b2_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a2aeba2)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (a2aeba2)

See https://github.com/ThaliTester/TestResults/tree/72314330a2aeba2_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330a2aeba2(a2aeba2) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/72314330a2aeba2_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (816037d)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (816037d)

See https://github.com/ThaliTester/TestResults/tree/72314330816037d_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330816037d(816037d) has failed

See https://github.com/ThaliTester/TestResults/tree/72314330816037d_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (83713e2)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (83713e2)

See https://github.com/ThaliTester/TestResults/tree/7231433083713e2_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 7231433083713e2(83713e2) has failed

See https://github.com/ThaliTester/TestResults/tree/7231433083713e2_CI_test_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (bfa5938)

**Comment by ThaliTester** [comment]
Test (Success) 72314330 build is completed (bfa5938)

See https://github.com/ThaliTester/TestResults/tree/72314330bfa5938_CI_test_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 72314330bfa5938(bfa5938) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/72314330bfa5938_CI_test_czyzm/ for the logs

**Pull request closed without merging**
