### PR TITLE
Story 001 tompaana 22

### PR DESCRIPTION
**Pull request by tompaana**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/25)

### CODE REVIEW

**Comment by vjrantal** [comment]
I think it was a good idea to leveraging more the distinction between Log.i and Log.d. Helps looking at the logs afterwards.

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothConnector.java, line 333 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/25#-K50WKBtCv1eP7Q_1hFV:-K50WKBtCv1eP7Q_1hFW:-308258429) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/03474a8e3fcd5b4ef2dcfd5dd684eac0e033ee73/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothConnector.java#L333)):_
When using insecure BT sockets, are we actually doing authentication at this level?

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtils.java, line 21 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/25#-K50WUbPkj1RvPQE_Op2:-K50WUbPkj1RvPQE_Op3:2014250881) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/03474a8e3fcd5b4ef2dcfd5dd684eac0e033ee73/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtils.java#L21)):_
Did you check if it is possible to read this from https://github.com/android/platform_frameworks_base/blob/android-4.3_r2/core/java/android/bluetooth/BluetoothSocket.java#L92

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/25#-:-K50XAhWDi0z75K-LF0a:-936017657)_

**Comment by tobybrad** [comment]
At some point we’re going to have to make logging more formal and probably start using a modern log library.

**Comment by tompaana** [comment]
_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothConnector.java, line 333 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/25#-K50WKBtCv1eP7Q_1hFV:-K51E2dmuRSpFpGkdxyy:581305859) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/03474a8e3fcd5b4ef2dcfd5dd684eac0e033ee73/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothConnector.java#L333)):_
Note, this is when handshake has succeeded.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/25)_

**Comment by tompaana** [comment]
_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothConnector.java, line 333 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/25#-K50WKBtCv1eP7Q_1hFV:-K51EP4zVbZ0Sm0fPCnX:725164562) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/03474a8e3fcd5b4ef2dcfd5dd684eac0e033ee73/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothConnector.java#L333)):_
*nope. Granted, the name is a bit misleading. However, it's internal callback.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/25)_

**Comment by tompaana** [comment]
_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtils.java, line 21 [r3]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/25#-K50WUbPkj1RvPQE_Op2:-K51EkDcy9fNSPot-lP_:-47867479) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/03474a8e3fcd5b4ef2dcfd5dd684eac0e033ee73/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/BluetoothUtils.java#L21)):_
Now that I'm the master of making private matters public, I could probably do this as well. But it seems like using alternative channel apart from 1 have no positive impact. So let's not do it now.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/25)_

**Pull request merged**
