### PR TITLE
Fixed deadlock in DiscoveryManager and BleePeerDiscoverer (97)

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/98)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (4b659b1)

**Comment by ThaliTester** [comment]
Test (Fail) 93987156 build is completed (4b659b1)

See https://github.com/ThaliTester/TestResults/tree/939871564b659b1_Fixed_deadlock_in_DiscoveryManager_and_BleePeerDiscoverer__97__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6def023)

**Comment by ThaliTester** [comment]
Test (Success) 93987156 build is completed (6def023)

See https://github.com/ThaliTester/TestResults/tree/939871566def023_Fixed_deadlock_in_DiscoveryManager_and_BleePeerDiscoverer__97__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 939871566def023(6def023) has failed

See https://github.com/ThaliTester/TestResults/tree/939871566def023_Fixed_deadlock_in_DiscoveryManager_and_BleePeerDiscoverer__97__evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[BtConnectorLib/settings.gradle, line 2 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98#-KWjGpiu9RkFa-MWwIOr:-KWjGpivg4CriyJl2ni8:b-33efx8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/6def02333408ef515f4b43d45049a4ed5a919674/BtConnectorLib/settings.gradle#L2)):_

> ``` Gradle
> include ':btconnectorlib2'
> gradle.ext.version = "0.3.6-alpha";
> ```

NB: I thought we were finally going to get rid of this alpha nonsense? Why aren't we just releasing 0.3.7? I know... I know... that isn't this PR's problem but still.

---

_[NativeTestApp/app/build.gradle, line 42 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98#-KWjH11AHEc0Q5mg3_Bm:-KWjH11BI01VmkFFrWa2:b-g5xj0m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/6def02333408ef515f4b43d45049a4ed5a919674/NativeTestApp/app/build.gradle#L42)):_

> ``` Gradle
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     compile 'com.android.support:appcompat-v7:23.1.1'
>     compile(group: 'org.thaliproject.p2p.btconnectorlib', name: 'btconnectorlib2', version: '0.3.5', ext: 'aar')
> ```

Why is this dependent on 0.3.5 but the general library above is using 0.3.6-alpha?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98#-:-KWjHT3pduDvynuY1hOS:bnfp4nl)_

**Comment by vasilevskayaem** [comment]
:lgtm:

---

Reviewed 7 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98#-:-KWmE5DW9BqfWEc2ttbG:bnfp4nl)_

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[BtConnectorLib/settings.gradle, line 2 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98#-KWjGpiu9RkFa-MWwIOr:-KWmHTbsv5QgE7qBBaIF:b2qi81n) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/6def02333408ef515f4b43d45049a4ed5a919674/BtConnectorLib/settings.gradle#L2)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> NB: I thought we were finally going to get rid of this alpha nonsense? Why aren't we just releasing 0.3.7? I know... I know... that isn't this PR's problem but still.
> </details>
> Somewhere in the past we decided use alpha versions for the cases when we need library asap not to block others but the code wasn't reviewed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98)_

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98#-:-KWmItkpy2vjYrExa4KO:bnfp4nl)_

**Comment by larryonoff** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BleAdvertiser.java, line 287 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98#-KWmJoCBe7uznK0ypMZj:-KWmJoCBe7uznK0ypMZk:b-dpo0qw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/6def02333408ef515f4b43d45049a4ed5a919674/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BleAdvertiser.java#L287)):_

> ``` Java
>     private void notifyAdvertiserStateChanged(final boolean isStarted) {
>         Log.d(TAG, "notifyAdvertiserStateChanged: started =  " + isStarted + ". " + ThreadUtils.currentThreadToString());
>         boolean posted = ThreadUtils.postToMainHandler(new Runnable() {
> ```

what about renaming this method into `ThreadUtils.performOnMainThread`or `ThreadUtils.runOnMainThread` ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98)_

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (f51b479)

**Comment by evabishchevich** [comment]
Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BleAdvertiser.java, line 287 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98#-KWmJoCBe7uznK0ypMZj:-KWmOHl52_OjfI3ksQb9:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/6def02333408ef515f4b43d45049a4ed5a919674/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BleAdvertiser.java#L287)):_
<details><summary>

<i>Previously, larryonoff (larryonoff) wrote…</i></summary>



> what about renaming this method into `ThreadUtils.performOnMainThread`or `ThreadUtils.runOnMainThread` ?
> </details>
> Done.

---

_[NativeTestApp/app/build.gradle, line 42 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98#-KWjH11AHEc0Q5mg3_Bm:-KWmItk2YXjbh1XBocDZ:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/6def02333408ef515f4b43d45049a4ed5a919674/NativeTestApp/app/build.gradle#L42)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> Why is this dependent on 0.3.5 but the general library above is using 0.3.6-alpha?
> </details>
> Fixed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/98)_

**Comment by ThaliTester** [comment]
Test (Success) 93987156 build is completed (f51b479)

See https://github.com/ThaliTester/TestResults/tree/93987156f51b479_Fixed_deadlock_in_DiscoveryManager_and_BleePeerDiscoverer__97__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 93987156f51b479(f51b479) has failed

See https://github.com/ThaliTester/TestResults/tree/93987156f51b479_Fixed_deadlock_in_DiscoveryManager_and_BleePeerDiscoverer__97__evabishchevich/ for the fail logs

**Pull request merged**
