### PR TITLE
Reset singleton state in tests

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/103)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8e6f6eb)

**Comment by ThaliTester** [comment]
Test 99073715 (8e6f6eb) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99073715 build is completed (8e6f6eb)

See https://github.com/ThaliTester/TestResults/tree/990737158e6f6eb_Reset_singleton_state_in_tests_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 990737158e6f6eb(8e6f6eb) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/990737158e6f6eb_Reset_singleton_state_in_tests_evabishchevich/ for the logs

**Review by larryonoff — APPROVED** [review]
Reflection is bad, but we don't have time on removing reflection.

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/103)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/103#-:-KZbYiv1RNj2lEuwfzI0:bnfp4nl)*

**Pull request merged**
