### PR TITLE
Get proper Bluetooth Mac Address on Android O

### PR DESCRIPTION
**Pull request by lesn1kk**
Not sure about instrumented tests adjustment, I was unable to run it. 
Tested also on Android 6.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/111)

### CODE REVIEW

**Comment by enricogior** [comment]
My only concern is with the fact that we didn't run the test, beside that, it LGTM.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-:-KrjvNjwNY1x55vRLJ10:b-cxr02b)*

**Comment by enricogior** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111)*

**Comment by jareksl** [comment]
It looks like there is a problem with one of the UT:
```
mMockSharedPreferences.getBoolean(
    contains("require_handshake"),
    <any>
);
-> at org.thaliproject.p2p.btconnectorlib.ConnectionManagerSettingsTest.testLoad(ConnectionManagerSettingsTest.java:332)
Actually, there were zero interactions with this mock.
```

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-:-Ks2vnDntngLlXyl8jiG:bhn7t5y)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (91dfb46)

**Comment by ThaliTester** [comment]
Test 136226771 (91dfb46) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (91dfb46)

**Comment by ThaliTester** [comment]
Test 136226771 (91dfb46) build started.

**Comment by ThaliTester** [comment]
Test (Success) 136226771 build is completed (91dfb46)

See https://github.com/ThaliTester/TestResults/tree/13622677191dfb46_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 13622677191dfb46(91dfb46) has failed

See https://github.com/ThaliTester/TestResults/tree/13622677191dfb46_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the fail logs

**Comment by jareksl** [comment]
Please check and fix instrumentation tests. 
Tests run: 85,  Failures: 16

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-:-Ks3GZTP67zQdqoY_yQe:b-yf2ozt)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java, line 490 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-Ks4lM9pZJ7_zW4o8jbi:-Ks4lM9qoEJ6-59mP1oM:b5xyjmm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/91dfb46a979726d4e5ec3fda21374780314cffd4/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerTest.java#L490)):*
> ```Java
>         } else {
>             try {
>                 mServiceField = btAdapter.getClass().getDeclaredField("mService");
> ```

Can you please put the call to getDeclaredField both here and above into a single function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-:-Ks4lX2ONZSo1KUTxs_T:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0d299a8)

**Comment by ThaliTester** [comment]
Test 136226771 (0d299a8) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 136226771 build is completed (0d299a8)

See https://github.com/ThaliTester/TestResults/tree/1362267710d299a8_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fb44a15)

**Comment by ThaliTester** [comment]
Test 136226771 (fb44a15) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 136226771 build is completed (fb44a15)

See https://github.com/ThaliTester/TestResults/tree/136226771fb44a15_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6e43118)

**Comment by ThaliTester** [comment]
Test 136226771 (6e43118) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 136226771 build is completed (6e43118)

See https://github.com/ThaliTester/TestResults/tree/1362267716e43118_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dd07430)

**Comment by ThaliTester** [comment]
Test 136226771 (dd07430) build started.

**Comment by ThaliTester** [comment]
Test (Success) 136226771 build is completed (dd07430)

See https://github.com/ThaliTester/TestResults/tree/136226771dd07430_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 136226771dd07430(dd07430) has failed

See https://github.com/ThaliTester/TestResults/tree/136226771dd07430_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the fail logs

**Comment by enricogior** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-:-KsA5igiB5l7TSGJixpQ:bnfp4nl)*

**Comment by enricogior** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111)*

**Comment by yaronyg** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5d11d37)

**Comment by ThaliTester** [comment]
Test 136226771 (5d11d37) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 136226771 build is completed (5d11d37)

See https://github.com/ThaliTester/TestResults/tree/1362267715d11d37_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ae9d25c)

**Comment by ThaliTester** [comment]
Test 136226771 (ae9d25c) build started.

**Comment by ThaliTester** [comment]
Test (Success) 136226771 build is completed (ae9d25c)

See https://github.com/ThaliTester/TestResults/tree/136226771ae9d25c_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 136226771ae9d25c(ae9d25c) has failed

See https://github.com/ThaliTester/TestResults/tree/136226771ae9d25c_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (69b35c3)

**Comment by ThaliTester** [comment]
Test 136226771 (69b35c3) build started.

**Comment by ThaliTester** [comment]
Test 13622677169b35c3(69b35c3) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/13622677169b35c3_Get_proper_Bluetooth_Mac_Address_on_Android_O_mlesnic/ for the logs

**Comment by jareksl** [comment]
We should also make sure that all tests properly run on Android Oreo

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-:-KsIFbBt1PnufTZkQqJB:b-jslu1g)*

**Comment by jareksl** [comment]
and well also Android 5. Additionally you could also set MockitoJUnitRunner for classes in the utills package 
:lgtm: 

---

Reviewed 3 of 6 files at r1, 11 of 13 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/build.gradle, line 33 at r8](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-KsINE-UgV1--ASOjD1c:-KsINE-UgV1--ASOjD1d:b-bt8amp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/69b35c332469077b2402801993e9c3b5f64be9d5/BtConnectorLib/btconnectorlib2/build.gradle#L33)):*
> ```Gradle
> dependencies {
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     compile 'com.android.support:appcompat-v7:23.1.1'
> ```

NB: You could also update com.android.support:appcompat

---

*[BtConnectorLib/btconnectorlib2/build.gradle, line 37 at r8](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-KsINbhSy_4q0xqy0aGG:-KsINbhSy_4q0xqy0aGH:b3vsg91) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/69b35c332469077b2402801993e9c3b5f64be9d5/BtConnectorLib/btconnectorlib2/build.gradle#L37)):*
> ```Gradle
>     testCompile "org.mockito:mockito-core:1.9.5"
> 
>     androidTestCompile 'com.android.support:support-annotations:24.0.0'
> ```

NB: There is newer version of com.android.support:support-annotations available

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-:-KsIvbRyIXeQdtD4QHj1:bf2l5ea)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 11 of 13 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/111#-:-KsKIBXrXbBjvcnS-hlN:bnfp4nl)*

**Comment by schildbach** [comment]
I believe this reflection workaround does not work on Android 8.1.

**Comment by yaronyg** [comment]
@schildbach  - Not surprising. W eknew it would eventually stop working. The much bigger deal is that Bluetooth in general doesn't work at all reliably on Android for our use cases, especially when using phones from different manufacturers. At this point without something like M-87 I don't see much hope of using peer to peer radios on Android.

**Comment by schildbach** [comment]
@yaronyg Did you find another workaround for Android 8.1 and later?

**Comment by yaronyg** [comment]
Nope. We stopped trying. :( This project has been abandoned for quite some time.

**Pull request merged**
