### PR TITLE
Story 001

### PR DESCRIPTION
**Pull request by DrJukka**
changed the listener socket to be accepting incoming connections all the time, and to handle the handshake in array. Enabling multiple handshakes to be handled simultaneously.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/14)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnector.java, line 86 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mLm1y5m4fxIz8-GiQ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnector.java#L86)):</sup>
Should we really have a string like this in the production code? How would we make sure it gets updated one each release?



---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java, line 17 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mNrS0c_QhABpI2cdK)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java#L17)):</sup>
It should be BTHandshakeSocketThread 
Handshake is one word
And Thread is spelled as listed and not Tread



---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java, line 91 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mO8uMrN70DTmslO2p)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java#L91)):</sup>
/oitgoing/outgoing/



---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java, line 111 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mOYSYBOPsvQoDjsvp)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java#L111)):</sup>
/handShake/handshake/



---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java, line 122 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mOchLuIGQ-Rw4L0da)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java#L122)):</sup>
/JSON_ID_BTADDRES/JSON_ID_BTADDRESS/



---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTListenerThread.java, line 138 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mPnYp9mlrgo2qCgjW)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTListenerThread.java#L138)):</sup>
/mBTHandShakerList/mBTHandshakeList/



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14)

**Comment by DrJukka** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnector.java, line 86 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mLm1y5m4fxIz8-GiQ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnector.java#L86)):</sup>
Sure, should have taken it out. Just had to add some unique debugging to verify that the app actually loads the locally build version, and that each Cradle-refresh does actually re-fresh the library included in the project. The broken device brought some ill behavior, and I simply needed a way to be 100% certain I knew which code I was running.

Now, removed from the code.



---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java, line 17 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mNrS0c_QhABpI2cdK)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java#L17)):</sup>
Refactored the name to be BTHandshakeSocketThread.



---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java, line 91 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mO8uMrN70DTmslO2p)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java#L91)):</sup>
Done.



---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java, line 111 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mOYSYBOPsvQoDjsvp)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java#L111)):</sup>
Changed the handShake to handshake in all places could find.



---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java, line 122 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mOchLuIGQ-Rw4L0da)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTConnectToThread.java#L122)):</sup>
Done.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14)

**Comment by DrJukka** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTListenerThread.java, line 138 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2mPnYp9mlrgo2qCgjW)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d097e7cfdb9b3d11ba1518be3fe5bc6839c3d6ef/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTListenerThread.java#L138)):</sup>
Done.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14)

**Comment by yaronyg** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTListenerThread.java, line 119 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2rU1NTnpEzyspqY3Jj)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/16e316deed7a372fb62cc3581a25bc0a27983dc9/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTListenerThread.java#L119)):</sup>
Why are you calling who.setPeerAddress twice in a row?

Once you fix this single comment please consider this PR completed and ready for submission. Thanks!



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14)

**Comment by DrJukka** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTListenerThread.java, line 119 [r2]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14#-K2rU1NTnpEzyspqY3Jj)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/16e316deed7a372fb62cc3581a25bc0a27983dc9/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTListenerThread.java#L119)):</sup>
Done.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14)

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14)

**Comment by yaronyg** [comment]
:shipit: 



---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/14)

**Comment by vjrantal** [comment]
Done testing locally and in CI and this change does not seem to make anything worse.

The `story_001` branch in the main repository has been updated to use version 0.0.2 from Bintray that already has a version with this commit.

After merging this to `master`, the Bintray version 0.0.2 matches to `master` branch.

**Pull request merged**
