### PR TITLE
Checking feature support when setting discovery mode (fix for #72)

### PR DESCRIPTION
**Pull request by czyzm**
Discard here the changes for AbstractConnectivityManagerTest.java as it is part of PR #73.

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/74)

### CODE REVIEW

**Comment by czyzm** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/74#-KK8Vpq5VhMGjttBSBxi:-KK8Vpq5VhMGjttBSBxj:746483993) (no related file):_
Discard file AbstractConnectivityManagerTest.java as it is a part of other PR (#73).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/74)_

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/AbstractConnectivityManagerTest.java, line 27 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/74#-KKUKcITTpfa5tw6nY96:-KKUKcITTpfa5tw6nY97:1780611630) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/ccaafb72e817a79dfd1514531f582bb356aaec1e/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/AbstractConnectivityManagerTest.java#L27)):_

> ``` Java
> 
>         // first make sure bluetooth is not changing its state right now
>         long currentTimeout = 0;
> ```

Is this from the previous PR I just reviewed? It looks identical.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/74#-:-KKUKmwc_qQby2ETmon4:1417088721)_

**Comment by czyzm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/AbstractConnectivityManagerTest.java, line 27 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/74#-KKUKcITTpfa5tw6nY96:-KKhLpWG2_meQOwDielh:2016874474) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/ccaafb72e817a79dfd1514531f582bb356aaec1e/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/AbstractConnectivityManagerTest.java#L27)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> Is this from the previous PR I just reviewed? It looks identical.
> </details>
> Yes, this is from other PR. To be not reviewed here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/74)_

**Comment by czyzm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/AbstractConnectivityManagerTest.java, line 27 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/74#-KKUKcITTpfa5tw6nY96:-KKhM69r3HfXKeLZGElu:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/ccaafb72e817a79dfd1514531f582bb356aaec1e/BtConnectorLib/btconnectorlib2/src/androidTest/java/org/thaliproject/p2p/btconnectorlib/AbstractConnectivityManagerTest.java#L27)):_
<details><summary>

<i>Previously, czyzm wrote…</i></summary>



> Yes, this is from other PR. To be not reviewed here.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/74)_

**Pull request merged**
