### PR TITLE
Removed zombies

### PR DESCRIPTION
**Pull request by evabishchevich**
Changed order of notification about peers. Minor refactorings

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/100)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8860bce)

**Comment by ThaliTester** [comment]
Test 98737854 (8860bce) build started.

**Comment by ThaliTester** [comment]
Test (Success) 98737854 build is completed (8860bce)

See https://github.com/ThaliTester/TestResults/tree/987378548860bce_Removed_zombies_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 987378548860bce(8860bce) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/987378548860bce_Removed_zombies_evabishchevich/ for the logs

**Review by larryonoff — APPROVED** [review]

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 16 of 17 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerSettingsTest.java, line 144 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/100#-KZXQfPvvelVxgd7O7pZ:-KZXQfPvvelVxgd7O7p_:bju8hed) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/1adc07b64c9b9f85c55fffdfc35f7429fd6ff441/BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerSettingsTest.java#L144)):*
> ```Java
>     }
> 
>     @Ignore("We use listener on sharedPreferences.edit()  method, but in real code we already have sharep preferences editor")
> ```

NB:/sharep/shared

---

*[BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerSettingsTest.java, line 146 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/100#-KZXQnz_R90gRjqi4rVt:-KZXQnz_R90gRjqi4rVu:bbfw7pt) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/1adc07b64c9b9f85c55fffdfc35f7429fd6ff441/BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerSettingsTest.java#L146)):*
> ```Java
>     @Ignore("We use listener on sharedPreferences.edit()  method, but in real code we already have sharep preferences editor")
>     @Test
>     public void testListener() throws Exception {
> ```

NB: If we are ignoring this test then why keep it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/100#-:-KZXR6qtwEnRwjcKMy5V:bnfp4nl)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerSettingsTest.java, line 146 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/100#-KZXQnz_R90gRjqi4rVt:-KZ_fgZDq58c6X7Ra_-s:b-8juooi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/1adc07b64c9b9f85c55fffdfc35f7429fd6ff441/BtConnectorLib/btconnectorlib2/src/test/java/org/thaliproject/p2p/btconnectorlib/ConnectionManagerSettingsTest.java#L146)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

NB: If we are ignoring this test then why keep it?
</blockquote></details>

It is a reminder for the times when we will have Android code rewritten. The second point - it's easier to explain to reviewers in that way than just silently delete test and get the question "Why we just delete test? It doesn't look like a bad/silly test"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/100)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8bd2c9b)

**Comment by ThaliTester** [comment]
Test 98737854 (8bd2c9b) build started.

**Comment by ThaliTester** [comment]
Test (Success) 98737854 build is completed (8bd2c9b)

See https://github.com/ThaliTester/TestResults/tree/987378548bd2c9b_Removed_zombies_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 987378548bd2c9b(8bd2c9b) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/987378548bd2c9b_Removed_zombies_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
@yarong The real reason of the failure of the test from comment https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/pull/100#issuecomment-268586189 was problem described in #102. Fix is in #103

**Pull request merged**
