### PR TITLE
Removed stop logic from start method. Updated version to 0.3.3

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/83)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (48e450e)

**Comment by ThaliTester** [comment]
Test (Fail) 81321792 build is completed (48e450e)

See https://github.com/ThaliTester/TestResults/tree/8132179248e450e_Removed_stop_logic_from_start_method__Updated_version_to_0_3_3_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
@jareksl  @czyzm  please, add the 23.0.3 build tools to the CI

**Comment by yaronyg** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java, line 466 [r1]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/83#-KPEvvUHqmYBa6rvve6s:-KPEvvUHqmYBa6rvve6t:b-2cbn2a) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/d2b8f69b415cbc1f0bb522ee0a6228aa94b8b09e/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java#L466)):_

> ``` Java
>         mShouldBeAdvertising = startAdvertising;
> 
>         if (!mShouldBeScanning && !mShouldBeAdvertising) {
> ```

This code isn't just random though. It's meant to initialize the system correctly. With it gone how do we make sure that we reset state as required by the start? Start isn't idempotent, it can have multiple calls with different values. So if we had a call that had startDiscovery set to true and then a subsequent call with startDiscovery set to false how do we make sure we stopDiscovery?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/83)_

**Comment by jareksl** [comment]
@evabishchevich: VM updated. Build Tools, Revision 23.0.3

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7fffb67)

**Comment by ThaliTester** [comment]
Test (Success) 81321792 build is completed (7fffb67)

See https://github.com/ThaliTester/TestResults/tree/813217927fffb67_Removed_stop_logic_from_start_method__Updated_version_to_0_3_3_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 813217927fffb67(7fffb67) has failed

See https://github.com/ThaliTester/TestResults/tree/813217927fffb67_Removed_stop_logic_from_start_method__Updated_version_to_0_3_3_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a5214f1)

**Comment by ThaliTester** [comment]
Test (Success) 81321792 build is completed (a5214f1)

See https://github.com/ThaliTester/TestResults/tree/81321792a5214f1_Removed_stop_logic_from_start_method__Updated_version_to_0_3_3_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 81321792a5214f1(a5214f1) has failed

See https://github.com/ThaliTester/TestResults/tree/81321792a5214f1_Removed_stop_logic_from_start_method__Updated_version_to_0_3_3_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (0df9177)

**Comment by ThaliTester** [comment]
Test (Success) 81321792 build is completed (0df9177)

See https://github.com/ThaliTester/TestResults/tree/813217920df9177_Removed_stop_logic_from_start_method__Updated_version_to_0_3_3_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 813217920df9177(0df9177) has failed

See https://github.com/ThaliTester/TestResults/tree/813217920df9177_Removed_stop_logic_from_start_method__Updated_version_to_0_3_3_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a95f0ee)

**Comment by ThaliTester** [comment]
Test (Success) 81321792 build is completed (a95f0ee)

See https://github.com/ThaliTester/TestResults/tree/81321792a95f0ee_Removed_stop_logic_from_start_method__Updated_version_to_0_3_3_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 81321792a95f0ee(a95f0ee) has failed

See https://github.com/ThaliTester/TestResults/tree/81321792a95f0ee_Removed_stop_logic_from_start_method__Updated_version_to_0_3_3_evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
What is the status of this PR? It has been sitting for 19 days. We need to either finish it or forget it. @evabishchevich can you please clarify as to its status?

**Comment by evabishchevich** [comment]
We can close that. I'll provide a new PR with changes in BtLib when when we have all the tests passed on Android

**Pull request closed without merging**
