### PR TITLE
fix mListner zombies bug

### PR DESCRIPTION
**Pull request by vasilevskayaem**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin_btlibrary/99)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e9d63a8)

**Comment by ThaliTester** [comment]
Test 97325715 (e9d63a8) build started.

**Comment by ThaliTester** [comment]
Test (Success) 97325715 build is completed (e9d63a8)

See https://github.com/ThaliTester/TestResults/tree/97325715e9d63a8_fix_mListner_zombies_bug_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 97325715e9d63a8(e9d63a8) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/97325715e9d63a8_fix_mListner_zombies_bug_vasilevskayaem/ for the logs

**Comment by larryonoff** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java, line 1348 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99#-KYmXQ3s9zwb2Ok5xMVC:-KYmXQ3s9zwb2Ok5xMVD:bxbm4kg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/e9d63a8a9531b3ef7326ba85a580c15e9f11bc94/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java#L1348)):*
> ```Java
>         Log.d(TAG, "updateState: " + ThreadUtils.currentThreadToString());
>         DiscoveryMode discoveryMode = mSettings.getDiscoveryMode();
>         if(mBlePeerDiscoverer!=null){
> ```

fix spaces on this line and below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99)*

**Comment by larryonoff** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 141 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99#-KYmXeu_9Zr_-OukK9XP:-KYmXeu_9Zr_-OukK9XQ:b-2t9yqn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/e9d63a8a9531b3ef7326ba85a580c15e9f11bc94/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L141)):*
> ```Java
>     private static final int ADVERTISER_RESTART_MAX_ATTEMPTS = 5;
> 
>     public void setListener(BlePeerDiscoveryListener mListener) {
> ```

why we made this property not final ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99)*

**Comment by vasilevskayaem** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 141 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99#-KYmXeu_9Zr_-OukK9XP:-KYmaF5rOsP6FR4ISiFe:bxwffqh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/e9d63a8a9531b3ef7326ba85a580c15e9f11bc94/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L141)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary><blockquote>

why we made this property not final ?
</blockquote></details>

to have opportunity to change it. DiscoverManager (it's implement BlePeerDiscoveryListener) can set its BlePeerDiscoverer to null, but sometimes it's continue to receive messages from BlePeerDiscoverer, so app have to clean this listener. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99)*

**Comment by larryonoff** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java, line 141 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99#-KYmXeu_9Zr_-OukK9XP:-KYmbBzgzorYcGRXQGwx:b-4zv67o) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/e9d63a8a9531b3ef7326ba85a580c15e9f11bc94/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/internal/bluetooth/le/BlePeerDiscoverer.java#L141)):*
<details><summary><i>Previously, vasilevskayaem wrote…</i></summary><blockquote>

to have opportunity to change it. DiscoverManager (it's implement BlePeerDiscoveryListener) can set its BlePeerDiscoverer to null, but sometimes it's continue to receive messages from BlePeerDiscoverer, so app have to clean this listener. 
</blockquote></details>

I see. Just checked the usage of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c84c269)

**Comment by ThaliTester** [comment]
Test 97325715 (c84c269) build started.

**Comment by vasilevskayaem** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java, line 1348 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99#-KYmXQ3s9zwb2Ok5xMVC:-KYmcy14WEw6blnU8Eym:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/e9d63a8a9531b3ef7326ba85a580c15e9f11bc94/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java#L1348)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary><blockquote>

fix spaces on this line and below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99)*

**Comment by ThaliTester** [comment]
Test (Success) 97325715 build is completed (c84c269)

See https://github.com/ThaliTester/TestResults/tree/97325715c84c269_fix_mListner_zombies_bug_vasilevskayaem/ for the logs

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99#-:-KYmfurnfqSrBiCx57LF:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test 97325715c84c269(c84c269) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/97325715c84c269_fix_mListner_zombies_bug_vasilevskayaem/ for the logs

**Comment by larryonoff** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java, line 1219 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99#-KYmgbY034Riek9I_8J7:-KYmgbY034Riek9I_8J8:b-7nrkw8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c84c2695c702812b560324e14b9d3869f73c4a37/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java#L1219)):*
> ```Java
>         if (mBlePeerDiscoverer != null) {
>             mBlePeerDiscoverer.stopScannerAndAdvertiser();
>             mBlePeerDiscoverer.setListener(new BlePeerDiscoverer.BlePeerDiscoveryListener() {
> ```

Please leave a comment that this's temporary solution and needs to be fixed in _ticket_number_

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99)*

**Comment by vasilevskayaem** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java, line 1219 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99#-KYmgbY034Riek9I_8J7:-KYmj2gFsrOtukODOa-h:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin_btlibrary/blob/c84c2695c702812b560324e14b9d3869f73c4a37/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java#L1219)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary><blockquote>

Please leave a comment that this's temporary solution and needs to be fixed in _ticket_number_
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99)*

**Comment by evabishchevich** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin_btlibrary/99#-:-KYn-2wmZtZcPcHUomh6:bnfp4nl)*

**Comment by evabishchevich** [comment]
This PR doesn't really fix the problem, just detects strange behaviour

**Pull request merged**
